### ISSUE TITLE
Documentation tracker - v0.10.0

### ISSUE THREAD

**Issue by amarthadan** [api3dao/airnode#1605]
Airnode issues that need documentation:
- [x] https://github.com/api3dao/airnode/issues/1626
- [x] https://github.com/api3dao/airnode/issues/1594
- [x] https://github.com/api3dao/airnode/issues/1536
- [x] https://github.com/api3dao/airnode/issues/1527
- [x] https://github.com/api3dao/airnode/issues/1492
- [x] https://github.com/api3dao/airnode/issues/1473
- [x] https://github.com/api3dao/airnode/issues/1460
- [x] https://github.com/api3dao/airnode/issues/1458
- [x] https://github.com/api3dao/airnode/issues/1444
- [x] https://github.com/api3dao/airnode/issues/1443
- [x] https://github.com/api3dao/airnode/issues/1411
- [x] https://github.com/api3dao/airnode/issues/1406
- [x] https://github.com/api3dao/airnode/issues/1405
- [x] https://github.com/api3dao/airnode/issues/1404
- [x] https://github.com/api3dao/airnode/issues/1403
- [x] https://github.com/api3dao/airnode/issues/1393
- [x] https://github.com/api3dao/airnode/issues/1376
- [x] https://github.com/api3dao/airnode/issues/1375
- [x] https://github.com/api3dao/airnode/issues/1374
- [x] https://github.com/api3dao/airnode/issues/1337
- [x] https://github.com/api3dao/airnode/issues/1296
- [x] https://github.com/api3dao/airnode/issues/1284

Corresponding documentation issues:
- [x] https://github.com/api3dao/api3-docs/issues/1175
- [x] https://github.com/api3dao/api3-docs/issues/1129
- [x] https://github.com/api3dao/api3-docs/issues/1118
- [x] https://github.com/api3dao/api3-docs/issues/1131
- [x] https://github.com/api3dao/api3-docs/issues/1063
- [x] https://github.com/api3dao/api3-docs/issues/1064
- [x] https://github.com/api3dao/api3-docs/issues/1164
- [x] https://github.com/api3dao/api3-docs/issues/1031
- [x] https://github.com/api3dao/api3-docs/issues/1030
- [x] https://github.com/api3dao/api3-docs/issues/1004
- [x] https://github.com/api3dao/api3-docs/issues/1167
- [x] https://github.com/api3dao/api3-docs/issues/1159
- [x] https://github.com/api3dao/api3-docs/issues/1059
- [x] https://github.com/api3dao/api3-docs/issues/1048
- [x] https://github.com/api3dao/api3-docs/issues/1130
- [x] https://github.com/api3dao/api3-docs/issues/992
- [x] https://github.com/api3dao/api3-docs/issues/967
- [x] https://github.com/api3dao/api3-docs/issues/966
- [x] https://github.com/api3dao/api3-docs/issues/994
- [x] https://github.com/api3dao/api3-docs/issues/985
- [x] https://github.com/api3dao/api3-docs/issues/993

**Comment by dcroote** [comment]
All documentation tasks for v0.10 complete
