### ISSUE TITLE
Documentation tracker - v0.11.0

### ISSUE THREAD

**Issue by amarthadan** [api3dao/airnode#1610]
Airnode issues that need documentation:
- [x] https://github.com/api3dao/airnode/issues/1649
- [x] https://github.com/api3dao/airnode/issues/1635
- [x] https://github.com/api3dao/airnode/issues/1632
- [x] https://github.com/api3dao/airnode/issues/1579
- [x] https://github.com/api3dao/airnode/issues/1544
- [x] https://github.com/api3dao/airnode/issues/1437

Corresponding docuemntation issues:
- [x] https://github.com/api3dao/api3-docs/issues/1224
- [x] https://github.com/api3dao/api3-docs/issues/1212
- [x] https://github.com/api3dao/api3-docs/issues/1181
- [x] https://github.com/api3dao/api3-docs/issues/1215
- [x] https://github.com/api3dao/api3-docs/issues/1199
- [x] https://github.com/api3dao/api3-docs/issues/1190

**Comment by dcroote** [comment]
Closing as v0.11 has been released
