### ISSUE TITLE
Documentation tracker - v0.12.0

### ISSUE THREAD

**Issue by amarthadan** [api3dao/airnode#1645]
Airnode issues that need documentation:
- [x] https://github.com/api3dao/airnode/issues/1738
- [x] https://github.com/api3dao/airnode/issues/1717
- [x] https://github.com/api3dao/airnode/issues/1711
- [x] https://github.com/api3dao/airnode/issues/1695
- [x] https://github.com/api3dao/airnode/issues/1673

Corresponding docuemntation issues:
- [x] https://github.com/api3dao/vitepress-docs/issues/419
- [x] https://github.com/api3dao/vitepress-docs/issues/487
- [x] https://github.com/api3dao/vitepress-docs/issues/455
- [x] https://github.com/api3dao/vitepress-docs/issues/386
- [x] https://github.com/api3dao/vitepress-docs/issues/553

**Airnode issues that need documentation but don't have a correspoding documentation issue:**
- [x] https://github.com/api3dao/airnode/issues/1589
