### ISSUE TITLE
Documentation tracker - v0.14.0

### ISSUE THREAD

**Issue by amarthadan** [api3dao/airnode#1886]
Airnode issues that need documentation:
- [ ] https://github.com/api3dao/airnode/issues/1506
- [ ] https://github.com/api3dao/airnode/issues/1478
- [ ] https://github.com/api3dao/airnode/issues/1317

Corresponding docuemntation issues:
- [x] https://github.com/api3dao/vitepress-docs/issues/389
- [x] https://github.com/api3dao/vitepress-docs/issues/388
- [x] https://github.com/api3dao/vitepress-docs/issues/385

**Comment by dcroote** [comment]
Closing this outdated automated doc issue tracking
